
export const nameToTitle: { [key: string]: string } = {
	"antonio": "Antonio",
	"carlos": "Carlos",
	"carolina": "Carolina",
	"juan": "Juan",
	"juanita": "Juanita",
	"manuel": "Manuel",
	"pedro": "Pedro",
	"comprobante": "Comprobante",
	"contabilidad": "Contabilidad",
	"facturacion": "Facturación",
	"nomina": "Nómina",
	"recibo": "Recibo",
	"usuarios": "Usuarios",
	"404": "NotFound 404",
	"encodingError": "EncodingError",
	"memoryOutOfRange": "OutOfRange",
	"nullPointer": "NullPointer",
	"stackOverflow": "StackOverflow",
	"syntaxError": "SyntaxError",
}
